spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AstraRoleService
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: AstraRoleService

server:
  port: 8080

